#!/usr/bin/env python3
"""Generate the paper's evidence table — the engine writing its own paper's evidence.

For each condition question: the engine's authority-ranked literature (grounded_rank,
with ABSTAIN) paired with the matched verified personal signals. Emits markdown to
paper/evidence_table.md. Regenerate any time: python3 paper_evidence.py
"""
from __future__ import annotations

from pathlib import Path

from cross_query import match_signals
from grounded import grounded_rank, ids_of

HERE = Path(__file__).resolve().parent
OUT = HERE / "paper" / "evidence_table.md"

QUESTIONS = [
    ("Obstructive sleep apnea (OSA)", "obstructive sleep apnea nocturnal oxygen desaturation severity CPAP outcomes"),
    ("POTS / dysautonomia", "postural orthostatic tachycardia exercise intolerance heart rate diagnostic criteria"),
    ("hEDS / hypermobility", "hypermobile Ehlers-Danlos diagnostic criteria joint hypermobility Beighton"),
    ("MCAS", "mast cell activation syndrome diagnostic criteria tryptase"),
    ("ADHD / guanfacine", "guanfacine ADHD cardiovascular heart rate effects"),
    ("Hashimoto / thyroid", "Hashimoto hypothyroidism desiccated thyroid liothyronine dosing TSH"),
    ("Collagen / tendon loading", "collagen tendon loading vitamin C synthesis rehabilitation"),
]


def block(label: str, question: str) -> str:
    verdict, top_cos, results = grounded_rank(question, 3)
    lines = [f"### {label}", f"_query:_ `{question}`  ·  _verdict:_ **{verdict}** (top cos {top_cos:.3f})", ""]
    titles: list[str] = []
    if verdict == "ABSTAIN":
        lines += ["_Literature:_ **ABSTAIN** — no sufficiently relevant paper in corpus.", ""]
    else:
        lines.append("**Literature (authority-ranked):**")
        for i, (c, d, (tier, lab)) in enumerate(results, 1):
            titles.append(d.get("title", ""))
            lines.append(f"{i}. «{lab}» {(d.get('title') or '').strip()} — {ids_of(d)} (cos {c:.3f})")
        lines.append("")
    sigs = match_signals(question, titles)
    lines.append("**Your data (verified personal signals):**")
    lines += [f"- {s['metric']}: {s['value']}  _^{s['source']}_" for s in sigs] or ["- (none tagged)"]
    lines += ["", "**Verdict (confirm / contradict / can't-resolve):** _<fill: your data vs the criteria above>_", "", "---", ""]
    return "\n".join(lines)


def main() -> int:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    parts = [
        "# Evidence Table — auto-generated by the medical-research-corpus engine",
        "_Each block: the engine's authority-ranked literature for a condition, paired with your "
        "verified personal signals. Regenerate: `python3 paper_evidence.py`._",
        "", "---", "",
    ]
    for label, q in QUESTIONS:
        parts.append(block(label, q))
    OUT.write_text("\n".join(parts))
    print(f"[DONE] evidence table -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
